### ISSUE TITLE
Support VS Code for the Web

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/vscode-noir#37]
### Problem

When a user opens a GitHub repository through https://github.dev/ and attempts to install the [Noir Language Support extension](https://marketplace.visualstudio.com/items?itemName=noir-lang.vscode-noir) in it, he/she would be prompted with:
```
The 'Noir Language Support' extension is not available in Visual Studio Code for the Web.
```

### Happy Case

As a Noir developer, I want to use the extension in the manner of:

1. Visit a Noir project on GitHub (e.g. [noir-starter](https://github.com/noir-lang/noir-starter/))
2. Hit "."
3. Install Noir Language Support extension from the extension panel on the left
4. Navigate to my Noir program (e.g. noir-starter/next-hardhat/circuits/src/main.nr)
5. Enjoy the same set of features offered by the extension in local VS Code (e.g. syntax highlighting, warning / error indicators on save, code snippets)

so that I can easily view, write and debug Noir programs in web browsers.

### Alternatives Considered

As an MVP, we could support a subset (instead of full set) of features in step (5) above.

### Additional Context

[VS Code for the Web](https://code.visualstudio.com/docs/editor/vscode-web)

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Assigning `P-HIGH` to this issue, as this could greatly improve UX re learning Noir and quick development with Noir.

**Comment by Savio-Sou** [comment]
@kobyhallx brought up the point that this could require either:
- Separate vscode-noir code branches for local vs web, or
- Refactoring of the entire LSP codebase to support web

To discuss further on how to approach the problem. cc @kevaundray

**Comment by kobyhallx** [comment]
To clarify
> Refactoring of the entire LSP codebase

we would refactor LSP parts, server interactions etc, while still relying on wasm module bringing in functionality developed so far in Rust related to compilation process.

**Comment by kevaundray** [comment]
@Savio-Sou The usecase for this was so that developers did not need to set up their environment at in-person workshops/events. Dev containers are easier to implement so we are going with that and putting this low on the priority list. (It's still unclear if we ever need to implement this) 

The priority right now is to implement the features needed in the LSP -- I've already CC'd with @kobyhallx earlier this week regarding implementing go to definition.

**Comment by kobyhallx** [comment]
Also, the point of this was to do this in js so we enable better contracts for js based tooling. Doing this with the browser's first mindset was rather a bonus rather than a goal by itself.

**Comment by kevaundray** [comment]
Closing this as its no longer relevant, given we have codespaces
