### ISSUE TITLE
Plugin icon

### ISSUE THREAD

**Issue by phated** [noir-lang/vscode-noir#4]
### Problem

We should have a plugin icon. This needs to be a 128x128 png. I'm not sure if we could do an svg instead.

### Happy Case

The plugin should have a logo that matches the noir brand, instead of an empty default icon.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
[This](https://files.slack.com/files-tmb/T8P21L9SL-F057AJQ3PHS-9becc2424d/noir_logo_mountains_480.png) is what we currently uses as our GitHub org logo. Would that work?

**Comment by phated** [comment]
@Savio-Sou that is a 480x480 image and I don't feel comfortable just scaling it down. We should have Matt edit it to make it 128x128
