### ISSUE TITLE
VSCode Extension plugin not formatting on save (v0.0.11)

### ISSUE THREAD

**Issue by jzaki** [noir-lang/vscode-noir#75]
### Aim

Have .nr files autoformat on save

### Expected Behavior

.nr files auto-format on save with noir-lang extension v0.0.11 as it does on v0.0.9

### Bug

.nr files do not auto-format on save with noir-lang extension v0.0.11 as it does on v0.0.9

### To Reproduce

1. Open .nr file
2. Make it un-pretty
3. Save
4. v0.0.11 does NOT format
5. install version v0.0.9, save, does format .nr file

### Would you like to submit a PR for this Issue?

No

**Comment by jzaki** [comment]
`@lang:noir` settings (not general settings, not @ext setting) -> "format on save" defaults to **on** for the older version, and defaults to **off** for 0.0.11.  Which appears to explain the difference between versions.

**Comment by Savio-Sou** [comment]
Solution: Check the general VS Code "Format On Save" setting.

Thanks @jzaki 🙏
